language: node_js
node_js:
  - 6
  - 5
  - 4
env:
  - NODE_ENV=test
sudo: false
script:
  - npm run lint
  - npm run test:e2e
  - npm run test
after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
